from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

#Кнопки
n_1 = InlineKeyboardButton(f'Все расходы💰', callback_data='expenses_1')
n_2 = InlineKeyboardButton(f'💵Добавить расходы по категориям💵', callback_data='expenses_2')
n_3 = InlineKeyboardButton(f'Изменения с категориями🛠', callback_data='changes')


n_4 = InlineKeyboardButton(f'Такси🚖', callback_data='taxi')
n_5 = InlineKeyboardButton(f'Продукты🍔', callback_data='products')
n_6 = InlineKeyboardButton(f'Электроника💻', callback_data='electronics')
n_7 = InlineKeyboardButton(f'Связь📞', callback_data='connection')
n_8 = InlineKeyboardButton(f'Прочие расходы💳', callback_data='other expenses')
n_9 = InlineKeyboardButton(f'Назад🔙', callback_data='end')
n_10 = InlineKeyboardButton(f'Удалить⛔', callback_data='dell')
n_11 = InlineKeyboardButton(f'Внести💵', callback_data='add')
n_12 = InlineKeyboardButton(f'Удалить полностью все данные🚫', callback_data='dell_2')
n_13 = InlineKeyboardButton(f'Удалить расходы в конкретной категории❌', callback_data='dell_3')
n_14 = InlineKeyboardButton(f'Добавить💼', callback_data='add_categories')
n_15 = InlineKeyboardButton(f'Вернуться в меню👨‍💻', callback_data='back_menu')
n_16 = InlineKeyboardButton(f'Да✅', callback_data='yes')
n_17 = InlineKeyboardButton(f'Нет❌', callback_data='no')
n_18 = InlineKeyboardButton(f'Выйти⛔', callback_data='quit_fsm')
n_29 = InlineKeyboardButton(f'Занести данные в exsel-таблицу✅', callback_data='add_exsel')
n_30 = InlineKeyboardButton(f'Да✅', callback_data='yes_7')
n_31 = InlineKeyboardButton(f'Нет❌', callback_data='no_7')
#Кнопки ДА, НЕТ
n_19 = InlineKeyboardButton(f'Да✅', callback_data='yes_2')
n_20 = InlineKeyboardButton(f'Нет❌', callback_data='no_2')

n_21 = InlineKeyboardButton(f'Да✅', callback_data='yes_3')
n_22 = InlineKeyboardButton(f'Нет❌', callback_data='no_3')

n_23 = InlineKeyboardButton(f'Да✅', callback_data='yes_4')
n_24 = InlineKeyboardButton(f'Нет❌', callback_data='no_4')

n_25 = InlineKeyboardButton(f'Да✅', callback_data='yes_5')
n_26 = InlineKeyboardButton(f'Нет❌', callback_data='no_5')

n_27 = InlineKeyboardButton(f'Да✅', callback_data='yes_6')
n_28 = InlineKeyboardButton(f'Нет❌', callback_data='no_6')
#Клавиатура
kb = InlineKeyboardMarkup(row_width=1)
kb_2 = InlineKeyboardMarkup(row_width=1)
kb_dell = InlineKeyboardMarkup(row_width=1)
kb_add = InlineKeyboardMarkup(row_width=1)
kb_dell_2 = InlineKeyboardMarkup(row_width=1)
kb_back = InlineKeyboardMarkup(row_width=1)
kb_back_menu = InlineKeyboardMarkup(row_width=1)
kb_sure = InlineKeyboardMarkup(row_width=2)
kb_quit_fsm = InlineKeyboardMarkup(row_width=1)
kb_adm = InlineKeyboardMarkup(row_width=1)
kb_dell_cat = InlineKeyboardMarkup(row_width=1)
kb_sure_2 = InlineKeyboardMarkup(row_width=2)
kb_sure_3 = InlineKeyboardMarkup(row_width=2)
kb_sure_4 = InlineKeyboardMarkup(row_width=2)
kb_sure_5 = InlineKeyboardMarkup(row_width=2)
kb_sure_6 = InlineKeyboardMarkup(row_width=2)
kb_sure_7 = InlineKeyboardMarkup(row_width=2)
#Добавление кнопок
kb.add(n_1, n_2)
kb_2.add(n_14, n_9)
kb_dell.add(n_10)
kb_add.add(n_11)
kb_dell_2.add(n_12, n_13, n_9)
kb_back.add(n_10)
kb_back_menu.add(n_9)
kb_sure.add(n_16, n_17,n_9)
kb_quit_fsm.add(n_18)
kb_adm.add(n_3, n_29, n_9)
kb_dell_cat.add(n_4, n_5, n_6, n_7, n_8, n_9)
kb_sure_2.add(n_19, n_20, n_9)
kb_sure_3.add(n_21, n_22, n_9)
kb_sure_4.add(n_23, n_24, n_9)
kb_sure_5.add(n_25, n_26, n_9)
kb_sure_6.add(n_27, n_28, n_9)
kb_sure_7.add(n_30, n_31)